### ISSUE TITLE
Error open torrent file with Popcorn-Time-CE on Mac OS X Sierra

### ISSUE THREAD

**Issue by emergy** [PopcornTime-CE/desktop#109]
After apply [this](https://github.com/PopcornTimeCommunity/desktop/pull/107) patch, Popcorn-Time woking on Mac X Sierra.  But there is another problem. It does not work the opening of the torrent file using the Popcorn-Time-CE

```
[DEBUG] Popcorn Time CE 0.4.1-2 startup time: 2982.310ms
app.js:43 [INFO] Spawning new provider TorrentCache
app.js:43 [INFO] Loading torrent
app.js:53 [ERROR] TorrentCache.handletorrent() error: Error: ENOENT: no such file or directory, open 'file:///Users/emergy/Downloads/%5Bkinozal.tv%5Did1472404%20(11).torrent' file:///Users/emergy/Downloads/%5Bkinozal.tv%5Did1472404%20(11).torrentwin.error @ app.js:53
app.js:43 [INFO] Loading torrent: Error resolving torrent.
app.js:53 [ERROR] TypeError: Cannot read property 'get' of undefined TypeError: Cannot read property 'get' of undefined
    at child.onStateUpdate (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/lib/views/player/loading.js:94:61)
    at triggerEvents (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/vendor/backbone/backbone.js:354:57)
    at triggerApi (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/vendor/backbone/backbone.js:339:19)
    at eventsApi (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/vendor/backbone/backbone.js:137:14)
    at Backbone.Model.Events.trigger (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/vendor/backbone/backbone.js:329:5)
    at Backbone.Model.set (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/vendor/backbone/backbone.js:498:16)
    at Object.updateState (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/lib/providers/torrent_cache.js:282:28)
    at Object.handleError (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/lib/providers/torrent_cache.js:278:22)
    at chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/lib/providers/torrent_cache.js:142:37
    at ReadStream.done (chrome-extension://kpcmklbgeppiboddbkjidmogeadbpahn/src/app/common.js:51:13)
```

**Comment by emergy** [comment]
fix https://github.com/emergy/desktop/commit/754993a48a68ed6906b6f53425df130abf76c529
