### ISSUE TITLE
Watch button doesn't work when building from source code (All Platforms)

### ISSUE THREAD

**Issue by AndrejaN** [PopcornTime-CE/desktop#114]
Hi everyone,

under linux (debin) i tried to build linux arm executable file from the source code. I used these commands 
"git clone https://github.com/PopcornTime-CE/desktop.git
cd desktop
npm install
gulp build -p linuxarm" (also tried for win32, win64, osx32, osx64 same result)

After this the program started OK, but when i try to play any movie i'm clicking on the button Watch, i can't play anything,  i can choose player but i don't get the window that says "Starting Download, Ready and so on". Can someone help me? The Watch Trailer button works, and the movie trailer is played.

Thanks in advance

**Comment by tuudik** [comment]
Same issue, with latest updates from github. On OSX platform. Watch doesnt do anything.

**Comment by AndrejaN** [comment]
Does this problem occurred in the previous versions?

**Comment by blackPantherOS** [comment]
I have same problem. The watch button insensitive, debug nothing

**Comment by YIFYtorrents** [comment]
@aurimus I really appreciate your hard work for this community, but please review your code before posting. I think it was your god damned PR https://github.com/PopcornTimeCommunity/desktop/pull/83 that broke the watch button, the very key function of popcorn time. Of course I had to revert all your pull requests. I had no choice.

@blackPantherOS please check the code with the new commits again and tell me weather everything works again. Thx

PS: my nodejs / npm doesn't work - so I am not able to test the code.

EDIT: sorry @aurimus - your code doesnt seem to affect watch button. Need to revert the reverts

**Comment by blackPantherOS** [comment]
Watch button doesn't work :(
I thinking that maybe a nodejs module problem and not in code? I cheked Butter-project too and Watch-button wont work as well in butter.

This is a fresh [demonstration video ](www.blackpantheros.eu/~vector/temp/ptce-2016-12-23.mp4)of PTCE:

**Comment by homeslicesolutions-zz** [comment]
Me too, it's not working on Windows 10

**Comment by dorukarda** [comment]
i have the same problem.. :(

**Comment by homeslicesolutions-zz** [comment]
I have created PR #117  to fix this issue. 

BUT, PR #107 also would fix the issue. The PR fixes the Watch button, but the switching streaming options isn't working.  Seems like you are stuck with the HTML5 browser option no matter what you change the dropdown to. @RonCan can you see if that works for you?

**Comment by haroondilshad** [comment]
@homeslicesolutions #107 doesn't let you switch streaming on Sierra? or are you talking about #117 not letting you switch? In my tests, I can switch streaming just fine

**Comment by homeslicesolutions-zz** [comment]
#107 was not letting me switch, but I'll test further.  Ultimately, we should go with your PR at some point because we should start using the later version of NWJS.

**Comment by AndrejaN** [comment]
Confirmed. Working on osx Sierra (osx64). I'm trying other platforms later.
Later: Works on All platforms.

I'm closing the topic. Thank you all.

**Comment by tuudik** [comment]
@AndrejaN Does switching also work?

**Comment by AndrejaN** [comment]
I have reopen the issue, because i'm not sure how to update the **package.json** file on the GitHub and i think that previous revert from YIFYtorrents is not necessary.

@tuudik Yes, everything works. You can switch player and Watch button works for all of them.

Great work

**Comment by tuudik** [comment]
@AndrejaN How to get fixed release? Seems that current master not yet updated. Edit manually just like it's done in PRs? PR #107 and #117 should fix it?

**Edit:**
Just tried but it opens in HTML5 player, browser.

**Comment by AndrejaN** [comment]
I only used #117. I just copied the package.json and build with #117 package.  So, just download the current master code and replace package.json with #117. I'm not a major contributor to the code, that why i didn't update directly on the master code. So, i call people that are responsible for checking and rechecking the code to just replace the package.json file from #117 on the current master code in order to fix the Watch button.

I tried DLNA works, i tried VLC works, but when i click for PT-CE for the PT-CE payer it says the video could not be loaded, either because the server... or because the format is not supported. I don't know why is this. This is for All major platforms. 

I get browser for my ARM Raspberry PI device, because no codecs are installed on the RasPi, and that's why PT-CE redirects me to browser.

I hope i clarified some things.

**Comment by tuudik** [comment]
So I tried as following:

1. Cloned Master
2. Made changes according to PR #117 
3. npm install
4. node_modules/.bin/gulp build -p osx64

Result:
Watch button not working.

When I applied also changes from PR #107 then watch button worked, but anyway it started playing in browser.

**Comment by homeslicesolutions-zz** [comment]
I'm going to close #117,  we should start working with the newer NWJS package.  Also it does work for me as well. Let's move forward with #107

**Comment by tuudik** [comment]
@homeslicesolutions but no solution for switching player?

**Comment by homeslicesolutions-zz** [comment]
@tuudik, #107 allows me to switch now.  I had to fully clean out my node_modules and redo NPM install.

**Comment by tuudik** [comment]
Maybe I'm an idiot, but I tried again:

1. Deleted oled clone
2. Cloned Master
3. Made changes according to PR #107
4. npm install
5. node_modules/.bin/gulp build -p osx64

Result: Still it opens in browser.

In PT it says that it's streaming to VLC but it's not actaully.

**Comment by homeslicesolutions-zz** [comment]
@tuudik How are you "making changes according to PR" ?  did you do a git pull of that PR?  Also are you seeing any errors in the console log?  Maybe, we can continue this thread outside?  Since we're discussing the PR, maybe we should move the conversation to that thread.  Now in terms of the "watch" button, it is working for most of us yes?  Seems like we can close this issue

**Comment by tuudik** [comment]
@homeslicesolutions I'm doing same changes as in: https://github.com/PopcornTimeCommunity/desktop/pull/107/files

I'm not launching it with npm start.
I build and I launch it as regular application.

**Comment by homeslicesolutions-zz** [comment]
@tuudik Ok, and when you press F12 open console, are you seeing any errors as you switch?  See "generic.js", and check out the "setDevice" function. Debug there.

Anyone else having this issue?

**Comment by YIFYtorrents** [comment]
I have added some commits. 

1. rename Nacho Link to HTML5 Video because of confusion: https://github.com/PopcornTimeCommunity/desktop/commit/587093d51ff2699b0a9bf00fe737a0835d0c6b05
2. set popcorntime as default player: https://github.com/PopcornTimeCommunity/desktop/commit/fbf95635937b7308033965448e21e314708e64b9
3. open HTML5 Video Player with direct streaming url http://127.0.0.1:port https://github.com/PopcornTimeCommunity/desktop/commit/54560d7eac0b413889ed2be0867380388a297abe
4. fix HTML5 Video Player for TV shows

**Comment by YIFYtorrents** [comment]
@tuudik just update register.js according to my https://github.com/PopcornTimeCommunity/desktop/commit/92249268693ee381927c7062d991e98391098a10

**Comment by YIFYtorrents** [comment]
@tuudik @homeslicesolutions update register.js according to my commit, see here: https://github.com/PopcornTimeCommunity/desktop/commit/92249268693ee381927c7062d991e98391098a10

**Comment by tuudik** [comment]
Yay! Much better. Everything started to work nicely, after I cleaned the cache and settings in PCT.

**Comment by YIFYtorrents** [comment]
@tuudik and I am not even finished yet. I have just added a small plugin system to get a nice overview on what is actually installed (rarbg.to search, kat.cr search, anti virus scanner by bitsnoop, html5 video player by nachotime.to, watchlist by trakt, etc..)

Also make sure to check out the improved html5 video player - it now redirects directly to 127.0.0.1:port and is fast as hell. Try right click on html5 video player and get all the features of html5 video. Its very cool.

Update your code, check it out and let me know what you think...

**Comment by YIFYtorrents** [comment]
I am not able to build the app.

`npm start`

> Popcorn-Time-CE@0.4.1-1 start /home/user/Desktop/git/desktop
gulp run
Using gulpfile ~/Desktop/git/desktop/gulpfile.js
 Starting 'run'...
[TypeError: Object [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object] has no method 'findIndex']
Finished 'run' after 2.53 s

&nbsp;

`gulp build -p linuxarm`

```
Error: Unknown platform linuxarm
    at /home/user/Desktop/git/desktop/node_modules/nw-builder/lib/index.js:74:19
    at Array.forEach (native)
    at new NwBuilder (/home/user/Desktop/git/desktop/node_modules/nw-builder/lib/index.js:72:28)
    at Object.<anonymous> (/home/user/Desktop/git/desktop/gulpfile.js:9:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:198:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:190:9)
    at /usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:164:9
    at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:108:14
```

**Comment by blackPantherOS** [comment]
I can confirm fresh build and watch button is working on Linux32 / 64, but:
- Database import button does not working
- Miss previous config and favorites by new data path
- But watch button is working playing does not start :" Video could not be loaded, either because....." libffmpegsumo.so not compatible now

I have a other suggestion: The default Download Directory is /tmp/PopcornTime this not a lucky path when system use tmpfs. Better path is $HOME/tmp/...

**Comment by YIFYtorrents** [comment]
> But watch button is working playing does not start :" Video could not be loaded, either because....." libffmpegsumo.so not compatible now

that is strange, because libffmpegsumo.so still works for me. 

I tried watch button without libffmpegsumo.so but the app crashed without even giving me error msg. Anyways it works for me if I put libffmpegsumo.so in the popcorn time folder. I will make a new build for all plattforms tomorrow.

EDIT: the reason it works for me is because I am still using old nwjs

**Comment by blackPantherOS** [comment]
> EDIT: the reason it works for me is because I am still using old nwjs

yep.. the nwbuilder 0.18.0 no longer includes libffmpegsumo.so therefore playing in PTCE is unsuccessful

**Comment by YIFYtorrents** [comment]
the watch button still doesn't work for me. I press f12 and I found a peerflix error. The issue is caused by peerflix package.

**Comment by YIFYtorrents** [comment]
there's a new update available on reddit: https://www.reddit.com/r/PopcornTimeCE/comments/5ks9vt/0415_beta_new_years_eve_in_front_of_the_door_28/
