### ISSUE TITLE
Can't cancel Nacho broadcasting + format is not supported local playing + slow series query

### ISSUE THREAD

**Issue by blackPantherOS** [PopcornTime-CE/desktop#89]
Hi,

I build 4.1-1 on Linux 32bit and I tried playing to Nacho, this working fine but I can't cancel playing... 

When I tried local playing in PTCE I got : 
The video could not be loaded, either because the server or network failed or because the format is not supported"
I know the problem the libffmpegsumo.so but does not understand what is missing for correct build...

And when select the series tab the list is slow or run to timeout, the favorites moovie on the favorites page slow too 
"[%cWARNING%c] TVAPI endpoint '%s' failed." "color: orange;" "color: black;" "https://eztvapi.ml/"", source: app://host/src/app/app.js (48) 
[21203:0617/121939:INFO:CONSOLE(43)] ""[%cINFO%c] Request to TVApi" "color: blue;" "color: black;" "https://popcorntime.ws/api/eztv/shows/1?sort=seeds&limit=50&genre=All&order=-1"", source: app://host/src/app/app.js (43)

Other:
Found DLNA Device: %s at %s" "color: blue;" "color: black;" "[TV][LG]42LA620S-ZA" "192.168.0.101"", source: app://host/src/app/app.js (43)
BUT seemingly playing started to TV does not displayed the moovie on TV or any request to play

**Comment by YIFYtorrents** [comment]
> I build 4.1-1 on Linux 32bit and I tried playing to Nacho, this working fine but I can't cancel playing... 

that's a bug, the only way to stop download is to close the popcorn time window, I will try to fix it.

**Comment by YIFYtorrents** [comment]
> I know the problem the libffmpegsumo.so but does not understand what is missing for correct build...

Check out @sebasgarcep fix below.... I am going to contact popcorntime.ag and see why he has not yet applied the fix.

> The owner of `popcorntime.ag` should:
> 1. Download all the nwjs v0.12.3 zips from `http://dl.nwjs.io` (`nwjs-v0.12.3-linux-ia32.tar.gz`, `nwjs-v0.12.3-linux-x64.tar.gz`, `nwjs-v0.12.3-osx-ia32.zip`, `nwjs-v0.12.3-osx-x64.zip`, `nwjs-v0.12.3-win-ia32.zip`, `nwjs-v0.12.3-win-x64.zip`) and replace the `libffmpegsumo.so` file in it with the working one.
> 2. Set up an `apache2` server which will host these files. The `apache2` server will take these zips from `/var/www/html/v0.12.3/`, so create this folder and place the zips in it.
> 3. `service apache2 start`.
> 4. Set `downloadUrl` to the `apache2` server's address. It should preferably be hosted under a subdomain of `popcorntime.ag`.
> 
> That is the general idea. This is only a quick fix for developer ease. I will look into the issue in `videojs` and see if I can come up with anything.

source: https://github.com/PopcornTimeCommunity/desktop/issues/13#issuecomment-189747473

**Comment by blackPantherOS** [comment]
Thanks to many response
Yep, seems the series and favorites displaying not a valid bug maybe internet provider error, but the host available was in console... sorry

I will try rebuild libffmpegsumo

The playing on TV problem is still have with this error :

```
[29454:0618/171523:INFO:CONSOLE(53)] ""%c[%cERROR%c] Error: Invalid Args (402)" "color: black;" "color: red;" "color: black;" "Error: Invalid Args (402)\n    at /tmp/.org.chromium.Chromium.Zj5Rff/node_modules/upnp-mediarenderer-client/node_modules/upnp-device-client/index.js:141:21\n    at ConcatStream.\u003Canonymous\u003E (/tmp/.org.chromium.Chromium.Zj5Rff/node_modules/upnp-mediarenderer-client/node_modules/upnp-device-client/node_modules/concat-stream/index.js:36:43)\n    at emitNone (events.js:70:20)\n    at ConcatStream.emit (events.js:147:7)\n    at finishMaybe (/tmp/.org.chromium.Chromium.Zj5Rff/node_modules/upnp-mediarenderer-client/node_modules/upnp-device-client/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:475:14)\n    at endWritable (/tmp/.org.chromium.Chromium.Zj5Rff/node_modules/upnp-mediarenderer-client/node_modules/upnp-device-client/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:485:3)\n    at ConcatStream.Writable.end (/tmp/.org.chromium.Chromium.Zj5Rff/node_modules/upnp-mediarenderer-client/node_modules/upnp-device-client/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:455:41)\n    at IncomingMessage.onend (_stream_readable.js:489:10)\n    at IncomingMessage.g (events.js:240:16)\n    at emitNone (events.js:70:20)\n    at IncomingMessage.emit (events.js:147:7)"", source: app://host/src/app/app.js (53)
[29454:0618/171523:INFO:CONSOLE(105)] "Uncaught Error: Invalid Args (402)", source: app://host/src/app/lib/device/dlna.js (105)



```

**Comment by blackPantherOS** [comment]
Ok, I build a Butter from git, and the working fine the playing to TV without error.. if this help to you

**Comment by captainyarr** [comment]
I fixed the cancel button issue in the latest PR #111
